ads:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Ads:index" }

ads_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/Ads:show" }

ads_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Ads:new" }

ads_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/Ads:create" }
    methods:  POST

ads_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Ads:edit" }

ads_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/Ads:update" }
    methods:  [POST, PUT]

ads_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Ads:delete" }
    methods:  [POST, DELETE]
