servers-zone:
    path:     /
    defaults: { _controller: "AppBundle:Admin/ServersZone:index" }

servers-zone_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/ServersZone:show" }

servers-zone_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/ServersZone:new" }

servers-zone_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/ServersZone:create" }
    methods:  POST

servers-zone_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/ServersZone:edit" }

servers-zone_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/ServersZone:update" }
    methods:  [POST, PUT]

servers-zone_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/ServersZone:delete" }
    methods:  [POST, DELETE]
