<?php

namespace Dmcl\AppBundle\Repository;

/**
 * PresetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresetsRepository extends \Doctrine\ORM\EntityRepository
{
}
