<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RegUserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegUserLogRepository extends EntityRepository
{
    public function findLogs($id, $page, $rpp)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from('AppBundle:RegUserLog', 'u')
            ->where('u.user = :id')
            ->setParameter("id", $id)
            ->orderBy('u.date', 'desc')
            ->setFirstResult(($page-1) * $rpp)
            ->setMaxResults($rpp);

        return new Paginator($qb);
    }
}
