<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServersSessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServersSessionsRepository extends EntityRepository
{

    public function getCurrentSessions($server,$serverType){

        return $count = $this->createQueryBuilder("c")
            ->select('COUNT(c)')
            ->where("c.active=true")
            ->andWhere("c.serverId=:serverId")
            ->andWhere("c.serverType=:serverType")
            ->setParameter("serverId",$server)
            ->setParameter("serverType",$serverType)
            ->getQuery()
            ->getResult();
    }

    public function findForSessionFinished($startAt,$serverType)
    {
        $query= $this->createQueryBuilder("ss")
            ->select("ss")
            ->where("ss.active=true and ss.playStartAt <= :startAt and ss.serverType = :serverType")
            ->setParameter("startAt",$startAt)
            ->setParameter("serverType",$serverType);

        return $query->getQuery()->getResult();
    }

}
