<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitsRepository extends EntityRepository
{

    public function findVisit($entity) {
        $qb = $this->createQueryBuilder("v")
            ->select()
            ->where("v.page = :page")
            ->andWhere("v.visitedAt > :visitedAt")
            ->andWhere("v.ipAddress = :ipAddress")
            ->setParameter("page", $entity->getPage())
            ->setParameter("visitedAt", new \DateTime("now - 30 minutes"))
            ->setParameter("ipAddress", $entity->getIpAddress())
        ;

        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }

    public function findVisitsMonth() {
        $monthStart = new \DateTime('first day of this month');
        $monthEnd = new \DateTime('last day of this month');

        $qb = $this->createQueryBuilder("v")
            ->select()
            ->where("v.visitedAt < :endDate")
            ->andWhere("v.visitedAt > :startDate")
            ->setParameter("endDate", $monthEnd)
            ->setParameter("startDate", $monthStart)
            ->orderBy("v.visitedAt", "ASC");
        ;

        $result = $qb->getQuery()->getArrayResult();
        return $result;
    }

}
