<?php

namespace Dmcl\AppBundle\Repository;

/**
 * VodEpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodEpisodeRepository extends \Doctrine\ORM\EntityRepository
{
}
