<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VodGenresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VodGenresRepository extends EntityRepository
{
    /**
     * Funcion utilizada para obtener los generos de vides con sus paquetes
     * para aquellos paquetes activos.
     */
    public function findVodGenresWithVideoPackage($isAdmin, $id)
    {
		$qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('vodGenres, vodPackages, vods')
            ->from('AppBundle:VodGenres', 'vodGenres')
            ->join('vodGenres.vodPackages', 'vodPackages')
            ->join('vodPackages.vods', 'vods')
            ->andWhere('vodPackages.enabled = true')
            ->andWhere($qb->expr()->isNotNull('vodPackages.live'));
			if(!$isAdmin) {
				$qb->andWhere('vodPackages.owner=:owner')
				->setParameter('owner', $id);
			}
			//dump($qb->getQuery()->getParameters());die;
        return $qb->getQuery()->getResult();
    }
}
