<?php

namespace Proxies\__CG__\Dmcl\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Packages extends \Dmcl\AppBundle\Entity\Packages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'name', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'isTrial', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'credits', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'duration', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'durationIn', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'bouquets', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'canGenMag', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'outputFormats', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'maxConnections', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'canGenE2', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'status'];
        }

        return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'name', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'isTrial', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'credits', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'duration', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'durationIn', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'bouquets', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'canGenMag', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'outputFormats', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'maxConnections', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'canGenE2', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Packages' . "\0" . 'status'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Packages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTrial($isTrial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTrial', [$isTrial]);

        return parent::setIsTrial($isTrial);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsTrial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsTrial', []);

        return parent::getIsTrial();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredits($credits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredits', [$credits]);

        return parent::setCredits($credits);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredits', []);

        return parent::getCredits();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$duration]);

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurationIn($durationIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurationIn', [$durationIn]);

        return parent::setDurationIn($durationIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurationIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurationIn', []);

        return parent::getDurationIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setBouquets($bouquets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBouquets', [$bouquets]);

        return parent::setBouquets($bouquets);
    }

    /**
     * {@inheritDoc}
     */
    public function getBouquets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBouquets', []);

        return parent::getBouquets();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanGenMag($canGenMag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanGenMag', [$canGenMag]);

        return parent::setCanGenMag($canGenMag);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanGenMag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanGenMag', []);

        return parent::getCanGenMag();
    }

    /**
     * {@inheritDoc}
     */
    public function setOutputFormats($outputFormats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutputFormats', [$outputFormats]);

        return parent::setOutputFormats($outputFormats);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutputFormats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutputFormats', []);

        return parent::getOutputFormats();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxConnections($maxConnections)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxConnections', [$maxConnections]);

        return parent::setMaxConnections($maxConnections);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxConnections()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxConnections', []);

        return parent::getMaxConnections();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanGenE2($canGenE2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanGenE2', [$canGenE2]);

        return parent::setCanGenE2($canGenE2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanGenE2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanGenE2', []);

        return parent::getCanGenE2();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

}
