block-ip-country:
    path:     /
    defaults: { _controller: "AppBundle:Admin/BlockIpCountry:index" }

block-ip-country_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/BlockIpCountry:show" }

block-ip-country_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/BlockIpCountry:new" }

block-ip-country_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/BlockIpCountry:create" }
    methods:  POST

block-ip-country_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/BlockIpCountry:edit" }

block-ip-country_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/BlockIpCountry:update" }
    methods:  [POST, PUT]

block-ip-country_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/BlockIpCountry:delete" }
    methods:  [POST, DELETE]
