_after_login:
    path:  "%prefix%/{_locale}/_login"
    defaults: { _controller: AppBundle:Default:afterLogin}
    requirements:
        methods: GET

# fos_js_routing:
#     resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

home:
    path:  "%prefix%/{_locale}/home"
    defaults: { _controller: AppBundle:Default:index }
    requirements:
        methods: GET

validate:
    path:  "%prefix%/{_locale}/validate/{msg}"
    defaults: { _controller: AppBundle:Default:validate, msg:'test' }   

send_email:
    path:  "%prefix%/{_locale}/send_email"
    defaults: { _controller: AppBundle:Default:sendEmail }
    requirements:
        methods: POST

_home:
    path:   "%prefix%"
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: home }

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   "%prefix%/{_locale}"

app_api:
    resource: "@AppBundle/Resources/config/routing/api.yml"
    prefix:   /api/v1

app_stb:
    resource: "@StbBundle/Resources/config/routing.yml"
    prefix:   /tvbox

# fos_user_security:
#     resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#     prefix: "%prefix%/{_locale}"

# fos_user_profile:
#     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#     prefix: "%prefix%/{_locale}/account/profile"
#     defaults: {role_prefix:admin}

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: "%prefix%/{_locale}/register"

# fos_user_resetting:
#     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#     prefix: "%prefix%/{_locale}/resetting"

# fos_user_change_password:
#     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#     prefix: "%prefix%/{_locale}/account/profile"
#     defaults: {role_prefix:admin}

nginx_security:
    path: /nginx
    defaults: { _controller: AppBundle:NginxSecurity:check }
