<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelsPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelsPackageRepository extends EntityRepository
{

    public function findForSale(){
        return  $this->createQueryBuilder("cp")
            ->select("cp")
            ->where("cp.enabled=true")
            ->Andwhere("cp.owner=:owner")
            //->andWhere("cp.price>0")
            ->setParameter("owner","admin")
            ->getQuery()
            ->getResult();
    }

    public function findChannelsAvailableForAdd($id){
        return $this->createQueryBuilder("cp")
            ->where("cp.enabled =true")
            ->andWhere("cp.id not in (:id) and cp.owner=:owner")
            ->setParameter("id",$id)
            ->setParameter("owner","admin")
            ->getQuery()
            ->getResult();
    }
}
