<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends EntityRepository
{

    public function findByMacForStb($mac){
        return $this->createQueryBuilder("c")
            ->where("c.macs  LIKE :mac")
            ->setParameter("mac","%$mac%")
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
    public function findByIpForStb($ip){
        return $this->createQueryBuilder("c")
            ->where("c.ips  LIKE :ip")
            ->setParameter("ip","%$ip%")
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }

}
