<?php

namespace Dmcl\AppBundle\Repository;

use Dmcl\AppBundle\Entity\EpgChannels;
use Doctrine\ORM\EntityRepository;

/**
 * EpgChannelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpgChannelsRepository extends EntityRepository
{

    public function queryAllEpgChannels($epg){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT epgc FROM AppBundle:EpgChannels epgc WHERE epgc.epg = :epg')
            ->setParameter("epg",$epg);

        return $consulta;
//ORDER BY o.fecha_publicacion DESC
    }

    public function findAllEpgChannels($epg){
        return $this->queryAllEpgChannels($epg)->getResult();
    }

    public function listChannelEpg($idChannel)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('epg')
            ->from('AppBundle:Epg', 'epg')
            ->join('epg.channels', 'epgChannels')
            ->where('epgChannels.channel = :channel')
            ->setParameter('channel', $idChannel);

        return $qb->getQuery()->getArrayResult();
    }

    /**
     * Remove the EpgChannels in cascade. This function fix the php timeout issue.
     *
     * @param integer $id EpgChannels id
     */
    public function remove($id) {
        $query = $this->createQueryBuilder("qb")
            ->delete("AppBundle:Programme", "p")
            ->where("p.channel = " . $id);
        $query->getQuery()->execute();

        $query = $this->createQueryBuilder('qb')
            ->delete("AppBundle:EpgChannels", "ch")
            ->where("ch.id = " . $id);
        $query->getQuery()->execute();
    }

}
