<?php

namespace Dmcl\AppBundle\Repository;

/**
 * LineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLines($page, $rpp)
    {
        $em = $this->getEntityManager('xtreamcode');
        $sql = "SELECT l FROM AppBundle:Users l";

        $query = $em->createQuery($sql);
        $query->setFirstResult(($page-1)*$rpp)->setMaxResults($rpp);      

        return $query->getResult();
    }
}
