<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    public function getTotalOrders(){
        return $count = $this->createQueryBuilder("c")
            ->select('COUNT(c)')
            ->getQuery()
            ->getResult();
    }




    public function totalForDashboard(){
        $sales =    $this->createQueryBuilder("o")
            ->where("o.verified=true")
            ->andWhere("o.verifiedAt>=:now")
            ->setParameter("now",new \DateTime("now - 11 months"))
            ->orderBy("o.verifiedAt","ASC")
            ->getQuery()
            ->getResult();

        foreach ([11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0] as $d) {
            $dashboardSales[(new \DateTime("now - $d months"))->format("Ym")]=0;
        }

        foreach ($sales as $sale) {
            $dashboardSales[$sale->getverifiedAt()->format("Ym")]+=1;
        }
        return $dashboardSales;

    }
}
