<?php

namespace Dmcl\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegUserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegUserLogRepository extends EntityRepository
{
    public function findLogs($id, $page, $rpp)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('l')
            ->from('AppBundle:RegUserLog', 'l')
            ->orderBy('l.date', 'asc')
            ->setFirstResult(($page-1)*$rpp)->setMaxResults($rpp);  
           
        if($id){
            $qb->where('l.user = :id')
               ->setParameter("id", $id);
        } 
        
        return $qb->getQuery()->getResult();
    }
}
