<?php

namespace Dmcl\AppBundle\Repository;

use Dmcl\AppBundle\Entity\RegUsers;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegUsersRepository extends EntityRepository
{
    public function findResellers($id, $page, $rpp)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('u')
            ->from('AppBundle:RegUsers', 'u')
            ->orderBy('u.username', 'asc')
            ->setFirstResult(($page-1)*$rpp)->setMaxResults($rpp);  
            
        if($id){
            $qb->innerJoin('u.memberGroup', 'g')
                ->andWhere('g.isReseller = 1')
                ->andWhere('u.ownerId = :id')
                ->setParameter("id", $id);
        } 

        return $qb->getQuery()->getResult();
    }
    
    public function findUsers($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('u')
            ->from('AppBundle:RegUsers', 'u')
            ->innerJoin('u.memberGroup', 'g')
            ->andWhere('g.isReseller = 1')
            ->andWhere('u.ownerId = :id')
            ->setParameter("id", $id);

        return $qb->getQuery()->getResult();
    }
}
