<?php

namespace Proxies\__CG__\Dmcl\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PackagesLocal extends \Dmcl\AppBundle\Entity\PackagesLocal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'name', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'superReseller', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'status', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'credits', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'price', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'period', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'logo', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'logoFile', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'updatedAt', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'name', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'superReseller', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'status', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'credits', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'price', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'period', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'logo', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'logoFile', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'updatedAt', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\PackagesLocal' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PackagesLocal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperReseller($superReseller)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperReseller', [$superReseller]);

        return parent::setSuperReseller($superReseller);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuperReseller()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuperReseller', []);

        return parent::getSuperReseller();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredits($credits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredits', [$credits]);

        return parent::setCredits($credits);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredits', []);

        return parent::getCredits();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriod($period)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriod', [$period]);

        return parent::setPeriod($period);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriod', []);

        return parent::getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogoFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogoFile', []);

        return parent::getLogoFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogoFile($logoFile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogoFile', [$logoFile]);

        return parent::setLogoFile($logoFile);
    }

}
