<?php

namespace Proxies\__CG__\Dmcl\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Enigma2Devices extends \Dmcl\AppBundle\Entity\Enigma2Devices implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'mac', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'modemMac', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'localIp', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'publicIp', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'keyAuth', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'enigmaVersion', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'cpu', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'version', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'lversion', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'token', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'lastUpdated', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'watchdogTimeout', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'lockDevice', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'telnetEnable', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'ftpEnable', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'sshEnable', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'dns', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'rc', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'originalMac', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'device', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'mac', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'modemMac', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'localIp', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'publicIp', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'keyAuth', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'enigmaVersion', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'cpu', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'version', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'lversion', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'token', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'lastUpdated', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'watchdogTimeout', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'lockDevice', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'telnetEnable', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'ftpEnable', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'sshEnable', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'dns', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'rc', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'originalMac', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'device', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Enigma2Devices' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Enigma2Devices $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setMac($mac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMac', [$mac]);

        return parent::setMac($mac);
    }

    /**
     * {@inheritDoc}
     */
    public function getMac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMac', []);

        return parent::getMac();
    }

    /**
     * {@inheritDoc}
     */
    public function setModemMac($modemMac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModemMac', [$modemMac]);

        return parent::setModemMac($modemMac);
    }

    /**
     * {@inheritDoc}
     */
    public function getModemMac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModemMac', []);

        return parent::getModemMac();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalIp($localIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalIp', [$localIp]);

        return parent::setLocalIp($localIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalIp', []);

        return parent::getLocalIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicIp($publicIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicIp', [$publicIp]);

        return parent::setPublicIp($publicIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicIp', []);

        return parent::getPublicIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeyAuth($keyAuth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeyAuth', [$keyAuth]);

        return parent::setKeyAuth($keyAuth);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeyAuth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeyAuth', []);

        return parent::getKeyAuth();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnigmaVersion($enigmaVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnigmaVersion', [$enigmaVersion]);

        return parent::setEnigmaVersion($enigmaVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnigmaVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnigmaVersion', []);

        return parent::getEnigmaVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpu($cpu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpu', [$cpu]);

        return parent::setCpu($cpu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpu', []);

        return parent::getCpu();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLversion($lversion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLversion', [$lversion]);

        return parent::setLversion($lversion);
    }

    /**
     * {@inheritDoc}
     */
    public function getLversion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLversion', []);

        return parent::getLversion();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdated($lastUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdated', [$lastUpdated]);

        return parent::setLastUpdated($lastUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdated', []);

        return parent::getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setWatchdogTimeout($watchdogTimeout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWatchdogTimeout', [$watchdogTimeout]);

        return parent::setWatchdogTimeout($watchdogTimeout);
    }

    /**
     * {@inheritDoc}
     */
    public function getWatchdogTimeout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWatchdogTimeout', []);

        return parent::getWatchdogTimeout();
    }

    /**
     * {@inheritDoc}
     */
    public function setLockDevice($lockDevice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLockDevice', [$lockDevice]);

        return parent::setLockDevice($lockDevice);
    }

    /**
     * {@inheritDoc}
     */
    public function getLockDevice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLockDevice', []);

        return parent::getLockDevice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelnetEnable($telnetEnable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelnetEnable', [$telnetEnable]);

        return parent::setTelnetEnable($telnetEnable);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelnetEnable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelnetEnable', []);

        return parent::getTelnetEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setFtpEnable($ftpEnable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFtpEnable', [$ftpEnable]);

        return parent::setFtpEnable($ftpEnable);
    }

    /**
     * {@inheritDoc}
     */
    public function getFtpEnable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFtpEnable', []);

        return parent::getFtpEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setSshEnable($sshEnable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSshEnable', [$sshEnable]);

        return parent::setSshEnable($sshEnable);
    }

    /**
     * {@inheritDoc}
     */
    public function getSshEnable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSshEnable', []);

        return parent::getSshEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDns($dns)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDns', [$dns]);

        return parent::setDns($dns);
    }

    /**
     * {@inheritDoc}
     */
    public function getDns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDns', []);

        return parent::getDns();
    }

    /**
     * {@inheritDoc}
     */
    public function setRc($rc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRc', [$rc]);

        return parent::setRc($rc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRc', []);

        return parent::getRc();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalMac($originalMac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalMac', [$originalMac]);

        return parent::setOriginalMac($originalMac);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalMac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalMac', []);

        return parent::getOriginalMac();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevice(\Dmcl\AppBundle\Entity\Devices $device)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevice', [$device]);

        return parent::setDevice($device);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevice()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDevice();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevice', []);

        return parent::getDevice();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Dmcl\AppBundle\Entity\Users $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

}
