<?php

namespace Proxies\__CG__\Dmcl\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paypal extends \Dmcl\AppBundle\Entity\Paypal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'paypalName', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'shopIdPublicKey', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'secretKey', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'enabled', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'orders'];
        }

        return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'paypalName', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'shopIdPublicKey', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'secretKey', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'enabled', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\Paypal' . "\0" . 'orders'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paypal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaypalName($paypalName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaypalName', [$paypalName]);

        return parent::setPaypalName($paypalName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaypalName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaypalName', []);

        return parent::getPaypalName();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopIdPublicKey($shopIdPublicKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopIdPublicKey', [$shopIdPublicKey]);

        return parent::setShopIdPublicKey($shopIdPublicKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopIdPublicKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopIdPublicKey', []);

        return parent::getShopIdPublicKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecretKey($secretKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecretKey', [$secretKey]);

        return parent::setSecretKey($secretKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecretKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecretKey', []);

        return parent::getSecretKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\Dmcl\AppBundle\Entity\Orders $orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', [$orders]);

        return parent::addOrder($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\Dmcl\AppBundle\Entity\Orders $orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', [$orders]);

        return parent::removeOrder($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

}
