<?php

namespace Proxies\__CG__\Dmcl\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MagEvents extends \Dmcl\AppBundle\Entity\MagEvents implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'status', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'event', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'needConfirm', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'msg', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'rebootAfterOk', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'autoHideTimeout', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'sendTime', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'additionalServicesOn', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'anec', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'vclub', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'magDevice'];
        }

        return ['__isInitialized__', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'id', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'status', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'event', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'needConfirm', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'msg', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'rebootAfterOk', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'autoHideTimeout', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'sendTime', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'additionalServicesOn', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'anec', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'vclub', '' . "\0" . 'Dmcl\\AppBundle\\Entity\\MagEvents' . "\0" . 'magDevice'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MagEvents $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvent($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvent', [$event]);

        return parent::setEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvent', []);

        return parent::getEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeedConfirm($needConfirm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeedConfirm', [$needConfirm]);

        return parent::setNeedConfirm($needConfirm);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeedConfirm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeedConfirm', []);

        return parent::getNeedConfirm();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsg($msg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsg', [$msg]);

        return parent::setMsg($msg);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsg', []);

        return parent::getMsg();
    }

    /**
     * {@inheritDoc}
     */
    public function setRebootAfterOk($rebootAfterOk)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRebootAfterOk', [$rebootAfterOk]);

        return parent::setRebootAfterOk($rebootAfterOk);
    }

    /**
     * {@inheritDoc}
     */
    public function getRebootAfterOk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRebootAfterOk', []);

        return parent::getRebootAfterOk();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoHideTimeout($autoHideTimeout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoHideTimeout', [$autoHideTimeout]);

        return parent::setAutoHideTimeout($autoHideTimeout);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoHideTimeout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoHideTimeout', []);

        return parent::getAutoHideTimeout();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendTime($sendTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendTime', [$sendTime]);

        return parent::setSendTime($sendTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendTime', []);

        return parent::getSendTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdditionalServicesOn($additionalServicesOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdditionalServicesOn', [$additionalServicesOn]);

        return parent::setAdditionalServicesOn($additionalServicesOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdditionalServicesOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdditionalServicesOn', []);

        return parent::getAdditionalServicesOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnec($anec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnec', [$anec]);

        return parent::setAnec($anec);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnec', []);

        return parent::getAnec();
    }

    /**
     * {@inheritDoc}
     */
    public function setVclub($vclub)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVclub', [$vclub]);

        return parent::setVclub($vclub);
    }

    /**
     * {@inheritDoc}
     */
    public function getVclub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVclub', []);

        return parent::getVclub();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagDevice(\Dmcl\AppBundle\Entity\MagDevices $magDevice = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagDevice', [$magDevice]);

        return parent::setMagDevice($magDevice);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagDevice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagDevice', []);

        return parent::getMagDevice();
    }

}
